export const ADD_BUDGETPART = 'ADD_BUDGETPART'
export const REMOVE_BUDGETPART = 'REMOVE_BUDGETPART';
export const SET_BUDGETPARTS = 'SET_BUDGETPARTS';
export const FETCH_BUDGETPARTS_FAILED = 'FETCH_BUDGETPARTS_FAILED';

export const PURCHASE_BUDGET_START = 'PURCHASE_BUDGET_START';
export const PURCHASE_BUDGET_SUCCESS = 'PURCHASE_BUDGET_SUCCESS';
export const PURCHASE_BUDGET_FAIL = 'PURCHASE_BUDGET_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORDERS_START ='FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const FETCH_ACTIVITIES_START ='FETCH_ACTIVITIES_START';
export const FETCH_ACTIVITIES_SUCCESS = 'FETCH_ACTIVITIES_SUCCESS';
export const FETCH_ACTIVITIES_FAIL = 'FETCH_ACTIVITIES_FAIL';

export const ADD_ACTIVITY_START = 'ADD_ACTIVITY_START';
export const ADD_ACTIVITY_SUCCESS = 'ADD_ACTIVITY_SUCCESS';
export const ADD_ACTIVITY_FAIL = 'ADD_ACTIVITY_FAIL';
export const ADD_ACTIVITY_INIT = 'ADD_ACTIVITY_INIT';

